/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package guru.ioio.aop.plugin

import com.android.build.gradle.AppExtension
import com.android.build.gradle.AppPlugin
import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class AopPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        println("***AopPlugin init***")

        if (project.plugins.hasPlugin(AppPlugin::class.java)) {
            project.extensions.getByType(AppExtension::class.java)
                .registerTransform(AopTransform(project))
        }
    }


}
